--- #YAML:1.0
name: ExtUtils-MyPerlConfig
version: 0.01
author: ~
abstract: |-
  A modifiable snapshot of the current perl configuration
license: perl
requires:
  Config: 0
build_requires:
  Test: 0
provides:
  ExtUtils::MyPerlConfig:
    file: lib/ExtUtils/MyPerlConfig.pm
    version: 0.01
generated_by: Module::Build version 0.2608
