--- #YAML:1.0
name: Probe-Perl
version: 0.01
author:
  - Randy W. Sims <randys@thepierianspring.org>
  - |-
    Based partly on code from the Module::Build project, by Ken Williams
    <kwilliams@cpan.org> and others.
abstract: Information about the currently running perl
license: perl
requires:
  Config: 0
build_requires:
  Test: 0
provides:
  Probe::Perl:
    file: lib/Probe/Perl.pm
    version: 0.01
generated_by: Module::Build version 0.2608
